version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000

    environment:
      - DATABASE_HOSTNAME=${PROD_DATABASE_HOSTNAME}
      - DATABASE_PORT=${PROD_DATABASE_PORT}
      - DATABASE_PASSWORD=${PROD_DATABASE_PASSWORD}
      - DATABASE_NAME=${PROD_DATABASE_NAME}
      - DATABASE_USERNAME=${PROD_DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: