version: "3"
services:
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Expires21!!
      - POSTGRES_DB=poi_api_db
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Expires21!!
      - DATABASE_NAME=poi_api_db
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: bash -c "cd /usr/src && pytest --cov="." --cov-fail-under=80 && flake8 . --ignore E711,E302,F541,E712,W291 && black . --check && isort . --check-only"
    depends_on:
      - postgres

volumes:
  postgres-db: