"""add likes

Revision ID: 128b2bdc9fb5
Revises: fcc6d65883ec
Create Date: 2022-02-27 02:58:42.298035

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "128b2bdc9fb5"
down_revision = "fcc6d65883ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("poi_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["poi_id"], ["pois.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "poi_id"),
    )
    op.alter_column(
        "pois",
        "published",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "pois",
        "published",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_table("likes")
    # ### end Alembic commands ###
