"""add comments tables

Revision ID: ca205df0518c
Revises: 128b2bdc9fb5
Create Date: 2022-02-28 18:32:39.193583

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ca205df0518c"
down_revision = "128b2bdc9fb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("comment", sa.String(), nullable=False),
        sa.Column("commented_poi", sa.Integer(), nullable=False),
        sa.Column("published", sa.Boolean(), server_default="TRUE", nullable=False),
        sa.Column("creator", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["commented_poi"], ["pois.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["creator"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comments")
    # ### end Alembic commands ###
