"""update comment table

Revision ID: ec70e81241a2
Revises: ca205df0518c
Create Date: 2022-03-01 16:31:32.615362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec70e81241a2"
down_revision = "ca205df0518c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("poi_id", sa.Integer(), nullable=False))
    op.drop_constraint("comments_commented_poi_fkey", "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "pois", ["poi_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("comments", "commented_poi")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments",
        sa.Column("commented_poi", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        "comments_commented_poi_fkey",
        "comments",
        "pois",
        ["commented_poi"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("comments", "poi_id")
    # ### end Alembic commands ###
