name: Build-Verify

on: 
  push:
    branches:
      - develop
      - feature/*    
# Comment to test new pipeline
jobs:
  build:
    environment:
      name: poi-tracker-fastapi
    runs-on: ubuntu-latest
    steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: Install python version 3.9
          uses: actions/setup-python@v2
          with:
            python-version: "3.9"
        - name: update pip
          run: python -m pip install --upgrade pip
        - name: install all dependencies
          run: pip install -r requirements.txt

  build-test:
    environment:
      name: poi-tracker-fastapi
    needs: [build]
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
        - name: pulling git repo
          uses: actions/checkout@v2
        - name: Install python version 3.9
          uses: actions/setup-python@v2
          with:
            python-version: "3.9"
        - name: update pip
          run: python -m pip install --upgrade pip
        - name: install all dependencies
          run: pip install -r requirements.txt
        - name: test with pytest
          run: |
            pip install pytest
            python -m pytest --cov="." --cov-fail-under=80
        - name: Code Linting Check
          run: flake8 . --ignore E711,E302,F541,E712,W291
        - name: code quality check
          run: black . --check
        - name: dependency sort check
          run: isort . --check-only

